[project]
name = "ipyquiz"
version = "0.2.0"
description = "Quizzes for Jupyter"
dependencies = [
    "ipython",
    "ipywidgets",
    "requests"
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/ipyquiz"]