[project]
name = "mip_matching"
version = "0.0.1"
description = "Quizzes for Jupyter"
dependencies = [
    "ipython",
    "ipywidgets",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/ipyquiz"]